"""EOP10's pathd cores, ported into nagaspilot/controls: equivalence with EOP10's own outputs, and the one fix.

`eop_golden.json` was generated by running EOP10's ORIGINAL pathd modules (selfdrive/pathd/{lat_nudge,lon_nudge,predict}.py and
`compute_speed_reduction`) on the built clone, 2026-10-04. The ported code must reproduce it exactly.
"""
import json
import math
from pathlib import Path
from types import SimpleNamespace as NS

from nagaspilot.controls.ngp_lat_nudge import LatNudge
from nagaspilot.controls.ngp_lon_nudge import LonNudge
from nagaspilot.controls.ngp_predict import predict
from nagaspilot.controls.ngp_speed_reduction import compute_speed_reduction

G = json.loads((Path(__file__).parent / 'eop_golden.json').read_text())


def close(a, b):
  return all(abs(x - y) < 1e-9 for x, y in zip(a, b, strict=True))


def test_lat_nudge_reproduces_eop10_exactly():
  ln = LatNudge()
  ln.enabled = True
  for step in G['lat']['seq']:
    tk = [NS(dRel=d, yRel=y) for d, y in step['tracks']]
    assert close(ln.update(G['lat']['left'], G['lat']['right'], tk, G['lat']['v']), step['out'])
  ln2 = LatNudge()
  ln2.enabled = True
  for want in G['lat_fast']:
    assert close(ln2.update(G['lat']['left'], G['lat']['right'], [], 30.0), want)       # above the avoidance speed: no offsets


def test_lon_nudge_reproduces_eop10_exactly():
  lo = LonNudge()
  lo.enabled = True
  for step in G['lon']:
    drivable, occ, bike, tk, v = step['args']
    assert abs(lo.update(drivable, occ, bike, [NS(dRel=d, yRel=y, vRel=vr) for d, y, vr in tk], v, 0.0) - step['out']) < 1e-9


def test_predict_reproduces_eop10_exactly():
  cl = [NS(track_id=t, x=x, z=z, vx=vx, vz=vz) for t, x, z, vx, vz in G['predict']['in']]
  for got, want in zip(predict(cl, G['predict']['v_ego']), G['predict']['out'], strict=True):
    assert got.track_id == want[0] and close([got.current_x, got.current_z, got.time_to_collision, got.threat_level], [want[1], want[2], want[5], want[6]])
    assert close(got.future_x, want[3]) and close(got.future_z, want[4])


def objs(case):
  return [NS(trackId=t, dRel=d, yRel=y, vRel=vr, prob=p) for t, d, y, vr, p in case['objs']]


def test_speed_reduction_legacy_mode_reproduces_eop10s_always_zero_behaviour():
  for case in G['speed_reduction']:
    v = float('nan') if case['v'] is None else case['v']
    got = compute_speed_reduction(objs(case), None, v, G['max_depth'], legacy_scale_bug=True)
    if case['inf']:
      assert got == float('inf')
    else:
      assert got == case['out'] and abs(got) == 0.0            # EOP10: every threat gives a zero reduction


def test_the_fix_makes_the_reduction_apply_as_the_table_and_comments_intend():
  D = G['max_depth']

  def red(*o, v=25.0):
    return compute_speed_reduction([NS(trackId=1, dRel=d, yRel=y, vRel=vr, prob=p) for d, y, vr, p in o], None, v, D)
  assert red() == float('inf')
  mid = red((30.0, 0.5, -6.0, 0.9))                          # ratio 0.375 -> scale 0.6, closing 6, speed scale ~1.02
  assert -3.8 < mid < -3.5
  far = red((60.0, 0.5, -2.0, 0.9))                          # ratio 0.75 -> scale 0.3
  assert -0.8 < far < -0.4
  near = red((12.0, 0.0, -10.0, 0.9))                        # ratio 0.15 -> scale 1.0, clamped to MAX_SPEED_REDUCTION
  assert near == -5.0
  assert red((90.0, 0.0, -6.0, 0.9)) == 0.0                  # beyond max depth: scale 0
  assert red((30.0, 3.5, -6.0, 0.9)) == float('inf')          # outside the corridor
  assert red((30.0, 0.0, 2.0, 0.9)) == float('inf')           # pulling away
  assert red((30.0, 0.0, -6.0, 0.3)) == float('inf')          # low probability
  assert red((-5.0, 0.0, -6.0, 0.9)) == float('inf')          # behind
  assert red((30.0, 0.0, -6.0, 0.9), v=5.0) > -2.5 - 1e-9      # never more than half the speed
  assert math.isfinite(red((30.0, 0.0, -6.0, 0.9), v=float('nan')))
  assert red((30.0, 0.0, -6.0, 0.9), v=35.0) < mid           # more speed, stronger trim


def test_grid_hit_is_a_threat_too():
  got = compute_speed_reduction([], None, 20.0, 80.0, grid_hit=(10.0, 0.0, 0.9))
  assert got < 0.0
