"""EOP10's MTSC, MSLC, DDSC and TLSC, ported into nagaspilot/controls: equivalence with the ORIGINALS' recorded outputs.

`eop_golden_map.json` was generated by running EOP10's original modules (selfdrive/controls/lib/{mtsc,mslc,ddsc,tlsc}.py) on the
built clone, 2026-10-04. Checked first that each original really produces targets (none is dead; DDSC just has no publisher on EOP10).
"""
import json
import math
from pathlib import Path
from types import SimpleNamespace as NS

from nagaspilot.controls.ngp_curve_speed import blend_mtsc_vtsc, calculate_speed_for_curvature
from nagaspilot.controls.ngp_ddsc import DDSC
from nagaspilot.controls.ngp_mslc import MSLC
from nagaspilot.controls.ngp_mtsc import MTSC
from nagaspilot.controls.ngp_tlsc import TLSC

G = json.loads((Path(__file__).parent / 'eop_golden_map.json').read_text())


def same(a, b):
  if a is None or b is None:
    return a is b
  return abs(a - b) < 1e-9


def test_mtsc_reproduces_the_original():
  m = MTSC(enabled=True)
  for row in G['mtsc']:
    r = m.update(NS(upcomingCurvatureDEPRECATED=[NS(x=x, y=y) for x, y in row['curves']]), 25.0, 0.0, 0.0)
    assert same(r['v_target'], row['v_target']) and r['state'] == row['state'] and r['is_active'] == row['active']
    assert r['handover_to_vtsc'] == row['handover'] and abs(r['curvature'] - row['curvature']) < 1e-12
    assert same(None if r['distance'] == float('inf') else r['distance'], row['distance'])


def test_mslc_reproduces_the_original():
  s = MSLC(enabled=True)
  for row in G['mslc']:
    md = NS(speedLimit=row['speedLimit'], nextSpeedLimit=row['next'], nextSpeedLimitDistance=row['dist'])
    target, state = s.update(md, row['v'], row['drv'], row['t'], row['nav'])
    assert same(target, row['target']) and state == row['state']


def test_ddsc_reproduces_the_original():
  d = DDSC()
  for row in G['ddsc']:
    lim, unc, v, gas, lead, stop = row['in']
    cap = d.update(NS(safeSpeedLimitMps=lim, unconsciousActive=unc), NS(gasPressed=gas, vEgo=v, standstill=v < 0.2), lead, stop)
    assert same(cap, row['cap']) and same(d.a_limit, row['a']) and d.active == row['active'] and d.standstill_latched == row['latched']


def test_tlsc_reproduces_the_original():
  t = TLSC(enabled=True)
  for row in G['tlsc']:
    out = t.update_from(row['lead'], row['v'], [(s, c, d) for s, c, d in row['objs']])
    assert same(out, row['out'])


def test_curve_speed_helpers_and_the_handover_blend():
  assert math.isinf(calculate_speed_for_curvature(0.0005, 1.8)) and abs(calculate_speed_for_curvature(0.004, 1.8) - 21.213) < 1e-3
  assert blend_mtsc_vtsc(20.0, None, 300.0, 25.0, None, 0.05) == (20.0, None)             # MTSC alone beyond 200 m
  assert blend_mtsc_vtsc(None, 18.0, 100.0, 25.0, None, 0.05) == (18.0, None)             # VTSC alone
  assert blend_mtsc_vtsc(20.0, 18.0, 100.0, 25.0, None, 0.05)[0] == 18.0                  # inside 150 m: VTSC
  t, state = blend_mtsc_vtsc(20.0, 18.0, 180.0, 25.0, 25.0, 0.05)                        # transition zone, rate-limited from the cruise speed
  assert abs(t - (25.0 - 1.5 * 0.05)) < 1e-9 and state == t
  assert blend_mtsc_vtsc(None, None, 100.0, 25.0, None, 0.05) == (None, None)
