"""EOP params that are deliberately not settings controls.

Every `EOP*` key in `common/params_keys.h` must be either in descriptor.py or
here with a reason -- test_params_coverage.py enforces exactly that, so a param
can never go missing from the UI silently. It can only go missing *loudly*, by
someone adding it here.

TRIAGED holds keys with a real reason. UNTRIAGED is the honest bucket: keys
inherited from the C++ panel's coverage gap that nobody has classified yet. It
is expected to shrink to empty, and the test prints its size on every run so
the debt stays visible rather than becoming permanent.
"""

from __future__ import annotations

# key -> why it is not a user-facing setting
TRIAGED: dict[str, str] = {
  'EOPDDSCEnabled': 'Canonical EOP-origin switch for NGP MapSpeed; the EOP planner retains its existing distraction path.',
  'EOPPathdNudgesEnabled': 'NGP camera-only proposer adapter; EOP sensor nudges use EOPNudgeEnabled and must not be applied twice.',
  'EOPSharedSLCOffsets': 'NGP MapSpeed compatibility configuration; EOP speed-limit offsets retain their existing individual settings.',

  'EOPBLECornerPairs': 'Credential, identity or structured provisioning data; never an ordinary on/off setting.',
  'EOPBLERadarPairingOpen': 'No verified switch consumer/semantics in this audit; see FEATURE_PARITY_AND_SWITCHES.md.',
  'EOPBLERadarRoster': 'Credential, identity or structured provisioning data; never an ordinary on/off setting.',
  'EOPBluetoothPairingActive': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPBluetoothPairingAddr': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPBluetoothPairingPin': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPCameraCalibrationParams': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPCarMake': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPCarType': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPCarVin': 'Credential, identity or structured provisioning data; never an ordinary on/off setting.',
  'EOPChestnutDrivingActive': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPChestnutDrivingEnabled': 'No verified switch consumer/semantics in this audit; see FEATURE_PARITY_AND_SWITCHES.md.',
  'EOPChestnutDrivingLoading': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPCurrentMCAPRoute': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPDriveMode': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPEgpuDrivingActive': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPEgpuDrivingEnabled': 'No verified switch consumer/semantics in this audit; see FEATURE_PARITY_AND_SWITCHES.md.',
  'EOPEgpuDrivingLoading': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPFactoryCalibrationParams': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPLastGPSAltitude': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPLastGPSLatitude': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPLastGPSLongitude': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPNavDestination': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPNavDestinationWaypoints': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPNavPilotOAuthEmail': 'Credential, identity or structured provisioning data; never an ordinary on/off setting.',
  'EOPNavPilotOAuthToken': 'Credential, identity or structured provisioning data; never an ordinary on/off setting.',
  'EOPOpenBLTFirmwareVersion': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPOpenBLTState': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPOpenBLTUpdateAvailable': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPPowerSaverEntryDuration': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPSpeedLimitPolicy': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPSteamDAuthToken': 'Credential, identity or structured provisioning data; never an ordinary on/off setting.',
  'EOPSteamDControlRequest': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPSteamDGeofencePolygon': 'Credential, identity or structured provisioning data; never an ordinary on/off setting.',
  'EOPSteamDRemoteControl': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPTripDailyStats': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  'EOPUbloxAssistNowToken': 'Credential, identity or structured provisioning data; never an ordinary on/off setting.',
  'EOPUpdateStatus': 'Runtime state, action/configuration payload or specialized value; not an ordinary on/off setting.',
  "EOPVoiceProcessing": "Transient cloud worker state",
  "EOPVoiceRecording": "Transient voice capture state",
  "EOPVoiceWakeTrigger": "Transient waked activation event",
  "EOPSideRearCalibReset": "One-shot daemon trigger, not a toggle -- custom ButtonControl in device.py's Side/Rear Camera Calibration row.",
}

# Not yet classified. Populated from the current gap so the gate is meaningful
# from day one; entries move to TRIAGED (with a reason) or into descriptor.py.
UNTRIAGED: set[str] = {
  "EOPALCCSteeringModeOnBrake",
  "EOPAccelerationProfile",
  "EOPAdaptiveGapEnabled",
  "EOPAggressiveFollow",
  "EOPAggressiveJerk",
  "EOPBSDMinSpeed",
  "EOPBluetoothCANInterface",
  "EOPBluetoothPairWindow",
  "EOPCATManualSR",
  "EOPCATPersist",
  "EOPCurrentRegion",
  "EOPCurveSpeedDBPath",
  "EOPDeviceBeep",
  "EOPDeviceGoOffRoad",
  "EOPDeviceModelList",
  "EOPDeviceModelSelected",
  "EOPDeviceName",
  "EOPFactoryCalibrated",
  "EOPFeatureAdvancedAnalytics",
  "EOPFeatureAiRouting",
  "EOPFeatureCloudBackup",
  "EOPFeatureCrossDeviceSync",
  "EOPFeatureDrivingScore",
  "EOPFeatureEmergencyAlert",
  "EOPFeatureFleetMode",
  "EOPFeatureLiveLocationShare",
  "EOPFeatureLiveTraffic",
  "EOPFeatureObdDashboard",
  "EOPFeaturePriorityTiles",
  "EOPFeatureRemoteCamera",
  "EOPFeatureRouteReplay",
  "EOPFeatureTelemetry",
  "EOPFeatureTripSync",
  "EOPFollowingDistance",
  "EOPGroundEnabled",
  "EOPIgnitionOn",
  "EOPLCABSMEnabled",
  "EOPLCAConfirmRequired",
  "EOPLCASurroundOverride",
  "EOPLanguage",
  "EOPLatRoadEdgeDetection",
  "EOPLonExtRadar",
  "EOPMSLCAlert",
  "EOPMSLCOffsetFixed",
  "EOPMSLCOffsetPercent",
  "EOPMicAdaptiveLoudness",
  "EOPMultiCameraCalibEnabled",
  "EOPNavEnabled",
  "EOPNavPilotAddress",
  "EOPNavPilotPaired",
  "EOPParkingMode",
  "EOPRearCameraHeight",
  "EOPRearCameraWidth",
  "EOPRecordSnap",
  "EOPRecorddImpactSensitivity",
  "EOPRecorddParkingHours",
  "EOPRecorddPostBufferSec",
  "EOPRecorddPreBufferSec",
  "EOPRecorddQuality",
  "EOPRecorddSnapAutoG",
  "EOPRecorddSnapImuMs",
  "EOPRelaxedFollow",
  "EOPRelaxedJerk",
  "EOPRoadHDR",
  "EOPSGMMapPath",
  "EOPSLCOffset1",
  "EOPSLCOffset2",
  "EOPSLCOffset3",
  "EOPSLCOffset4",
  "EOPSLCOffset5",
  "EOPSLCOffset6",
  "EOPSLCOffset7",
  "EOPSPPChannel",
  "EOPSPPDeviceName",
  "EOPSPPMaxClients",
  "EOPSPPPairedDevice",
  "EOPSPPRpcRequest",
  "EOPSPPRpcResponse",
  "EOPSQSCProfile",
  "EOPSQSCRecordMinLeadM",
  "EOPSQSCRecordMinQuality",
  "EOPSQSCRecordMinSpeedKph",
  "EOPSQSCSensitivity",
  "EOPSQSCSmoothing",
  "EOPSafetyDriverTorqueThreshold",
  "EOPSafetyEventLogPath",
  "EOPSafetyHeartbeatTimeout",
  "EOPSafetyMaxAccel",
  "EOPSafetyMaxAngleError",
  "EOPSafetyMaxSteeringAngle",
  "EOPSafetyMaxSteeringRate",
  "EOPSafetyMessageTimeout",
  "EOPSafetyMinAccel",
  "EOPShockDepthM",
  "EOPShockDetection",
  "EOPShockDuration",
  "EOPShockHeightM",
  "EOPShockSpeedLimit",
  "EOPShockThreshold",
  "EOPSideCameraHeight",
  "EOPSideCameraWidth",
  "EOPSimPlatform",
  "EOPSimScenario",
  "EOPSimWeather",
  "EOPSpeedLimitOffset",
  "EOPStandardFollow",
  "EOPStandardJerk",
  "EOPSubscriptionCheckInterval",
  "EOPSubscriptionDeviceId",
  "EOPSubscriptionExpiry",
  "EOPSubscriptionSignature",
  "EOPSubscriptionSkipVerify",
  "EOPSubscriptionTier",
  "EOPSubscriptionToken",
  "EOPSurfaceLongRange",
  "EOPTJAMaxHoldMinutes",
  "EOPTSCTargetLatAccelMedium",
  "EOPTSCTargetLatAccelMild",
  "EOPTSCTargetLatAccelSharp",
  "EOPTTSVoice",
  "EOPTTSVolume",
  "EOPTeleHDR",
  "EOPTileLastUpdate",
  "EOPTouchEventNode",
  "EOPTrafficFollow",
  "EOPTrafficJerk",
  "EOPTripAStartDistance",
  "EOPTripAStartTime",
  "EOPTripBStartDistance",
  "EOPTripBStartTime",
  "EOPTripCurrentEngagementRatio",
  "EOPTripLastDistance",
  "EOPTripLastDuration",
  "EOPTripLastMaxAccel",
  "EOPTripLastOverrideFreeDistance",
  "EOPTripLastPersonalityTime",
  "EOPTripLifetimeEngagementRatio",
  "EOPTripMode",
  "EOPTripTotalDistance",
  "EOPTripTotalDrives",
  "EOPTripUptimeEngaged",
  "EOPTripUptimeOnroad",
  "EOPUIBrightness",
  "EOPUIRadarTracks",
  "EOPUIRainbow",
  "EOPUploadCurrentHeaders",
  "EOPUploadCurrentId",
  "EOPUploadCurrentPath",
  "EOPUploadCurrentProgress",
  "EOPUploadCurrentSize",
  "EOPUploadCurrentUrl",
  "EOPValhallaUrl",
  "EOPVehicleType",
  "EOPWideHDR",
}


def excluded_keys() -> frozenset[str]:
  return frozenset(TRIAGED) | frozenset(UNTRIAGED)
