#!/usr/bin/env python3
import argparse
import json
import os
from pathlib import Path

from openpilot.common.basedir import BASEDIR

UI_DIR = os.path.join(BASEDIR, "selfdrive", "ui")
TRANSLATIONS_DIR = os.path.join(UI_DIR, "translations")
LANGUAGES_FILE = os.path.join(TRANSLATIONS_DIR, "languages.json")
TRANSLATIONS_INCLUDE_FILE = os.path.join(TRANSLATIONS_DIR, "alerts_generated.h")
TRANSLATIONS_INCLUDE_PY = os.path.join(TRANSLATIONS_DIR, "alerts_generated.py")
PLURAL_ONLY = ["main_en"]  # base language, only create entries for strings with plural forms


def ui_is_python() -> bool:
  """True when this branch's UI is the Python one.

  dev/EOP10 keeps the C++/Qt UI; dev/01M and dev/02M replaced it with a Qt
  Widgets UI in Python. The extraction tool differs -- lupdate parses C++,
  pylupdate5 parses Python -- and running the wrong one silently extracts
  nothing, which is what left the Python branches unable to pick up any
  newly added string.
  """
  return not any(Path(UI_DIR).rglob(ext) for ext in ("*.cc", "*.h"))


def _offroad_alert_texts() -> list[str]:
  with open(os.path.join(BASEDIR, "selfdrive/selfdrived/alerts_offroad.json")) as f:
    return [alert["text"] for alert in json.load(f).values()]


def generate_translations_include():
  """Emit the offroad-alert strings in a form the extractor can see.

  The alerts live in JSON, so neither extractor would find them on its own.
  """
  # TODO translate events from openpilot.selfdrive/controls/lib/events.py
  if ui_is_python():
    content = (
      "# THIS IS AN AUTOGENERATED FILE, PLEASE EDIT alerts_offroad.json\n"
      + "from PyQt5.QtCore import QCoreApplication\n\n"
    )
    for text in _offroad_alert_texts():
      content += f'QCoreApplication.translate("OffroadAlert", {text!r})\n'
    out = TRANSLATIONS_INCLUDE_PY
  else:
    content = "// THIS IS AN AUTOGENERATED FILE, PLEASE EDIT alerts_offroad.json\n"
    for text in _offroad_alert_texts():
      content += f'QT_TRANSLATE_NOOP("OffroadAlert", R"({text})");\n'
    out = TRANSLATIONS_INCLUDE_FILE

  with open(out, "w") as f:
    f.write(content)


def update_translations(vanish: bool = False, translation_files: None | list[str] = None, translations_dir: str = TRANSLATIONS_DIR):
  if translation_files is None:
    with open(LANGUAGES_FILE) as f:
      translation_files = json.load(f).values()

  python_ui = ui_is_python()
  for file in translation_files:
    tr_file = os.path.join(translations_dir, f"{file}.ts")
    if python_ui:
      # pylupdate5 takes sources explicitly -- it has no -recursive -- and
      # supports neither -locations nor -pluralonly.
      sources = " ".join(sorted(str(p) for p in Path(UI_DIR).rglob("*.py")))
      args = f"pylupdate5 {'-noobsolete ' if vanish else ''}{sources} -ts {tr_file}"
    else:
      args = f"lupdate -locations none -recursive {UI_DIR} -ts {tr_file} -I {BASEDIR}"
      if vanish:
        args += " -no-obsolete"
      if file in PLURAL_ONLY:
        args += " -pluralonly"
    ret = os.system(args)
    assert ret == 0


if __name__ == "__main__":
  parser = argparse.ArgumentParser(description="Update translation files for UI",
                                   formatter_class=argparse.ArgumentDefaultsHelpFormatter)
  parser.add_argument("--vanish", action="store_true", help="Remove translations with source text no longer found")
  args = parser.parse_args()

  generate_translations_include()
  update_translations(args.vanish)
