#!/usr/bin/env bash
# Regenerates INVENTORY.md for the final upstream-delta audit.
# Usage: ./gen_inventory.sh  (run from repo root or this directory)
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

BASE=c085b8af1
TIP=88a04bc76
OUT=docs/upstream-audit/FINAL_AUDIT_2026-06-10/INVENTORY.md
AUDIT_DOCS=$(ls docs/upstream-audit/*.md | grep -v FINAL_AUDIT)

{
echo "# Change Inventory: \`$BASE\` (upstream) → \`$TIP\` (EOP10)"
echo
echo "Generated by \`gen_inventory.sh\`. Columns: adds/dels (\`-\` = binary), hunks (M files only),"
echo "xref = mentioned in a prior docs/upstream-audit review doc."
echo

for STATUS in M A D; do
  case $STATUS in
    M) TITLE="Modified upstream files";;
    A) TITLE="Added files (EOP-new)";;
    D) TITLE="Deleted upstream files";;
  esac
  echo "## $TITLE"
  echo
  echo "| path | +/− | hunks | xref |"
  echo "|---|---|---|---|"
  git diff --name-only --diff-filter=$STATUS $BASE..$TIP | while read -r f; do
    NS=$(git diff --numstat $BASE..$TIP -- "$f" | awk '{print $1"/"$2}')
    HUNKS=""
    if [ "$STATUS" = M ]; then
      if [[ "$NS" == -/- ]]; then HUNKS=bin
      else HUNKS=$(git diff --unified=0 $BASE..$TIP -- "$f" | grep -c '^@@' || true); fi
    fi
    XREF=$(grep -l -F "$f" $AUDIT_DOCS 2>/dev/null | head -1 | xargs -r basename || true)
    echo "| \`$f\` | $NS | $HUNKS | ${XREF:--} |"
  done
  echo
done

echo "## Renames / type changes"
echo
echo '```'
git diff --name-status --diff-filter=RT $BASE..$TIP
echo '```'
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
