#pragma once

#include <string>
#include <unordered_map>

#include "cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT, BOOL}},
    {"DisableUpdates", {PERSISTENT, BOOL}},
    {"DisengageOnAccelerator", {PERSISTENT, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"AlphaLongitudinalEnabled", {PERSISTENT | DEVELOPMENT_ONLY, BOOL}},
    // ASM2464PD USB eGPU driving path (mirrors upstream UsbGpu*; named after
    // the hardware, not comma's Chestnut model class -- we support both our
    // own flashed firmware and comma's on the same physical chip).
    {"EOPEgpuDrivingEnabled", {PERSISTENT, BOOL}},
    {"EOPEgpuDrivingLoading", {CLEAR_ON_MANAGER_START, BOOL}},
    {"EOPEgpuDrivingActive", {CLEAR_ON_MANAGER_START, BOOL}},
    {"ExperimentalMode", {PERSISTENT, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"EOPPowerSaverEntryDuration", {PERSISTENT, INT, "30"}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT, STRING}},
    {"GithubUsername", {PERSISTENT, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT, STRING}},
    {"GsmMetered", {PERSISTENT, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT, BOOL}},
    {"IsMetric", {PERSISTENT, BOOL}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsOnroad", {PERSISTENT, BOOL}},
    {"EOPQuietMode", {PERSISTENT, BOOL, "0"}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTakingSnapshot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT, STRING, "main_en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT, BOOL}},
    {"ngp_dashboard_enabled", {PERSISTENT, BOOL, "0"}},
    {"ngp_device_shutdown_minutes", {PERSISTENT, INT, "-1"}},
    {"ngp_device_logger_delay_seconds", {PERSISTENT, INT, "0"}},
    {"ngp_device_audible_mode", {PERSISTENT, INT, "0"}},
    {"ngp_ui_hide_hud_speed_kph", {PERSISTENT, INT, "0"}},
    {"ngp_ui_brightness", {PERSISTENT, INT, "0"}},
    {"ngp_device_vehicle_selected", {PERSISTENT, STRING, ""}},
    {"ngp_device_vehicle_list", {CLEAR_ON_MANAGER_START, STRING, "[]"}},
    {"ngp_lat_alcc", {PERSISTENT, BOOL, "0"}},
    // DLAT (Dynamic Lateral Profile, nagaspilot/controls/ngp_dlat.py) is a
    // default, always-on behavior of this branch -- automatic Laneful/
    // Laneless confidence arbitration only, no user-selectable mode param.
    // DLP curve assist: pre-emptively force laneless on a predicted tight
    // curve (NGPDLAT.update_model()'s curve_assist_enabled), ahead of the
    // ordinary confidence hysteresis. Matches EOP10's EOPDLPCurvesEnabled,
    // including its default-on.
    {"ngp_lat_dlp_curves", {PERSISTENT, BOOL, "1"}},
    // Pause lateral assistance with a turn signal on below this speed (mph); 0 = off.
    {"ngp_lat_blinker_pause_mph", {PERSISTENT, INT, "0"}},
    // Notice when the car is released from a planner stop (green light). Default off.
    {"ngp_lon_green_light", {PERSISTENT, BOOL, "0"}},
    // SOC: small slow offset away from a vehicle beside you on the highway (ngp_soc.py). Default off.
    {"ngp_lat_soc", {PERSISTENT, BOOL, "0"}},
    // RED: vision-only curvature nudge away from a close road edge in laneless mode (ngp_red.py).
    // ExoPilot adds YOLO/stereo corroboration. Unvalidated on road; default off.
    {"ngp_lat_edge_guard", {PERSISTENT, BOOL, "0"}},
    {"ngp_lat_lca_auto_sec", {PERSISTENT, FLOAT, "0.0"}},
    // Lane turn desire: max speed (mph) at which a turn signal sends a turn desire to the model; 0 = off.
    {"ngp_lat_turn_desire_mph", {PERSISTENT, INT, "0"}},
    // Opt-in LCA guards from modelV2: adjacent-lane TTC gap, target-lane width (>= 2.5 m).
    {"ngp_lat_lca_gap_eval", {PERSISTENT, BOOL, "0"}},
    {"ngp_lat_lca_lane_width", {PERSISTENT, BOOL, "0"}},
    // CAT: smoothed and validated steer ratio / stiffness from liveParameters. Default off.
    {"ngp_lat_cat", {PERSISTENT, BOOL, "0"}},
    {"ngp_lat_lca_speed", {PERSISTENT, INT, "20"}},
    {"ngp_lat_road_edge_detection", {PERSISTENT, BOOL, "0"}},
    // BRSC: Bumpy Road Speed Controller — shared verbatim across EOP10/NGP10/EDP10
    // via nagaspilot/controls/ngp_brsc.py. See docs/eop/03_Software/Controllers/BRSC.md on dev/EOP10.
    // Notice when the lead pulls away while stopped (radarState only). Default off.
    {"ngp_lon_lead_departure", {PERSISTENT, BOOL, "0"}},
    // Driver-activity decay: relaxed/tight; strict retains the deployed relaxed table.
    {"ngp_dm_policy", {PERSISTENT, STRING, "strict"}},
    // monod (nagaspilot/runtime/monod.py): road-camera YOLO detections, publish-only. Default off; needs a detector model compiled in.
    // Cut-in speed trim (ngp_cutin_speed.py): lowers cruise speed for a predicted cut-in seen by monod. Default off; needs ngp_monod_enabled.
    {"ngp_lon_cutin", {PERSISTENT, BOOL, "0"}},
    // pathd add-on (nagaspilot/runtime/pathd.py): publishes pathAdjust (lateral offset + speed factor). Publish-only, default off.
    // pathd add-on consumers (ngp_pathd_consumer.py), default off, need ngp_pathd_enabled: lateral offset in controlsd, speed cap in the planner.
    {"ngp_lat_pathd", {PERSISTENT, BOOL, "0"}},
    {"ngp_lon_pathd", {PERSISTENT, BOOL, "0"}},
    // DPP ceiling for the parallel rule channel (0 idle, 1 shadow, 2 supervise, 3 primary long, 4 primary lat, 5 primary both). DPP picks the mode by case inside it. Needs ngp_pathd_enabled.
    {"ngp_dpp_max_mode", {PERSISTENT, INT, "0"}},
    // pathd: also run the ported EOP10 proposers (LatNudge, LonNudge, speed reduction) from camera-only inputs (nagaspilot/runtime/nudge_extras.py). Default off; needs ngp_pathd_enabled.
    {"ngp_pathd_nudges", {PERSISTENT, BOOL, "0"}},
    // Map / light / distraction speed caps (nagaspilot/runtime/map_speed.py), all default off, they only lower the cruise speed.
    // tripd (nagaspilot/runtime/tripd.py): trip statistics; EOP10 keeps its EOPTrip* names through its shim. Process behind ngp_tripd_enabled.
    {"ngp_tripd_enabled", {PERSISTENT, BOOL, "0"}},
    {"ngp_trip_a_start_distance", {PERSISTENT, FLOAT, "0.0"}},
    {"ngp_trip_a_start_time", {PERSISTENT, FLOAT, "0.0"}},
    {"ngp_trip_b_start_distance", {PERSISTENT, FLOAT, "0.0"}},
    {"ngp_trip_b_start_time", {PERSISTENT, FLOAT, "0.0"}},
    {"ngp_trip_last_distance", {PERSISTENT, FLOAT, "0.0"}},
    {"ngp_trip_last_duration", {PERSISTENT, FLOAT, "0.0"}},
    {"ngp_trip_last_max_accel", {PERSISTENT, FLOAT, "0.0"}},
    {"ngp_trip_last_override_free_distance", {PERSISTENT, FLOAT, "0.0"}},
    {"ngp_trip_last_personality_time", {PERSISTENT, STRING, ""}},
    {"ngp_trip_lifetime_engagement_ratio", {PERSISTENT, FLOAT, "0.0"}},
    {"ngp_trip_total_distance", {PERSISTENT, FLOAT, "0.0"}},
    {"ngp_trip_total_drives", {PERSISTENT, INT, "0"}},
    {"ngp_trip_daily_stats", {PERSISTENT, STRING}},  // JSON {date: [distance, onroad_time, engaged_time, drives]}, last 7 days
    {"ngp_trip_uptime_engaged", {PERSISTENT, FLOAT, "0.0"}},
    {"ngp_trip_uptime_onroad", {PERSISTENT, FLOAT, "0.0"}},
    {"ngp_map_enabled", {PERSISTENT, BOOL, "0"}},    // mapd: OSM tiles for MTSC/MSLC (uses the public Overpass servers; see docs)
    // Canonical EOP-origin names; ngp_* entries below remain legacy read aliases.
    {"EOPMTSCEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPMSLCEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPTLSCEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPDDSCEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPRCDEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPSharedSLCOffsets", {PERSISTENT, STRING, ""}},
    {"EOPPathdNudgesEnabled", {PERSISTENT, BOOL, "0"}},
    {"ngp_lon_mtsc", {PERSISTENT, BOOL, "0"}},      // curve speed from OSM curvature (needs mapd)
    {"ngp_lon_mslc", {PERSISTENT, BOOL, "0"}},      // posted speed limit from OSM (needs mapd)
    {"ngp_lon_tlsc", {PERSISTENT, BOOL, "0"}},      // stop for a red/yellow light on our path (needs monod + gridd)
    {"ngp_lon_ddsc", {PERSISTENT, BOOL, "0"}},      // speed cap while the driver-activity monitor says the driver is not responding
    {"ngp_lon_rcd", {PERSISTENT, BOOL, "0"}},       // speed cap on a wet / icy / debris road (needs a surface source: surfaced or the camera-tier card)
    {"ngp_lon_slc_offsets", {PERSISTENT, STRING, ""}},   // MSLC offsets in km/h per posted-limit bucket, e.g. "5,5,5,5,5,5,5"
    {"ngp_pathd_enabled", {PERSISTENT, BOOL, "0"}},
    {"ngp_monod_enabled", {PERSISTENT, BOOL, "0"}},
    {"ngp_monod_hz", {PERSISTENT, INT, "5"}},
    // Driving mode: eco / normal / sport set the acceleration profile, following style and adaptive gap together;
    // custom (default) writes nothing. See nagaspilot/controls/ngp_drive_mode.py.
    {"ngp_lon_drive_mode", {PERSISTENT, STRING, "custom"}},
    {"ngp_lon_accel_profile", {PERSISTENT, STRING, "normal"}},
    // Adaptive follow gap uses only the standard radarState.leadOne observation.
    // Default off like EOP10's EOPAdaptiveGapEnabled; opt-in pending vehicle validation.
    {"ngp_lon_adaptive_gap", {PERSISTENT, BOOL, "0"}},
    {"ngp_lon_brsc", {PERSISTENT, BOOL, "1"}},
    // pathd hosts the shared planner (nagaspilot/runtime/pathd.py: protection layer + rule channel + DPP) and publishes pathAdjust. Default off.
    // monod: range road-camera boxes on the road plane with a radar-anchored scale (nagaspilot/runtime/eop_monod_ranging.py) instead of the class-height prior. Default off until validate_ranging passes on a stereo route.
    {"ngp_monod_ranger", {PERSISTENT, BOOL, "0"}},
    // pathd: use the corrected distance-scale lookup in compute_speed_reduction. EOP10's original lookup never reduced speed (nagaspilot/controls/ngp_speed_reduction.py). Default off = behaviour unchanged.
    {"ngp_pathd_fix_scale", {PERSISTENT, BOOL, "0"}},
    // DPP ceiling (0 idle, 1 shadow, 2 supervise, 3 primary long, 4 primary lat, 5 primary both); DPP picks the mode by case inside it. Needs ngp_pathd_enabled.
    // DLON (Dynamic Longitudinal Profile) is a default, always-on behavior
    // of this branch -- automatic ACC/E2E switching only. No master enable
    // toggle and no mode param: users cannot force pure E2E (Experimental)
    // or pure ACC directly. The per-trigger toggles below only tune which
    // situational signals the automatic switch considers, not force a mode.
    {"ngp_lon_dlon_curves", {PERSISTENT, BOOL, "1"}},
    {"ngp_lon_dlon_force_stops", {PERSISTENT, BOOL, "1"}},
    // Couples DLAT's own Laneful/Laneless arbitration (see ngp_lat above) into
    // DLON's automatic switch: when DLAT has committed to Laneless, E2E's
    // path-only prediction fits better than lane-line-anchored ACC.
    {"ngp_lon_dlon_lane_confidence", {PERSISTENT, BOOL, "1"}},
    {"ngp_lon_dlon_low_speed", {PERSISTENT, BOOL, "1"}},
    {"ngp_lon_dlon_navigation", {PERSISTENT, BOOL, "1"}},
    {"ngp_lon_dlon_signal", {PERSISTENT, BOOL, "1"}},
    {"ngp_lon_dlon_slow_lead", {PERSISTENT, BOOL, "1"}},
    {"ngp_lon_dlon_speed_limit", {PERSISTENT, BOOL, "1"}},
    {"ngp_lon_dlon_stop_prediction", {PERSISTENT, BOOL, "1"}},
    // Lane Change Lead Handoff: pure-camera adjacent-lane lead tracking during
    // laneChangeStarting (nagaspilot/controls/ngp_lc_lead_handoff.py). No panel
    // toggle by design, matching EOP10's EOPLCAdjacentLeadHandoff. Default off.
    {"ngp_lon_lc_lead_handoff", {PERSISTENT, BOOL, "0"}},
    // NSLC-equivalent: clamp cruise speed to the posted navigation speed
    // limit (nagaspilot/controls/ngp_speed_policy.py, NAVIGATION policy).
    // Nav-only -- NGP10 has no map-data source (see
    // nagaspilot/docs/EOP10_PARITY_CANDIDATES.md's Tier 2.5). No panel
    // toggle, matching EOP10's EOPNSLCEnabled. Default off.
    {"ngp_lon_nslc", {PERSISTENT, BOOL, "0"}},
    // Driver preference: constant kph offset applied to the final v_cruise
    // (after all other limits), matching EOP10's EOPSpeedLimitOffset and its
    // driver_prefs.py::get_speed_with_offset() application point. Default 0
    // is a no-op, so this needs no separate enable flag. EOP10's
    // driver_prefs.py also has a following_distance/get_time_gap() concept,
    // but it's never actually called anywhere in EOP10's own
    // longitudinal_planner.py -- dead code there too, not ported here.
    {"ngp_lon_speed_offset_kph", {PERSISTENT, INT, "0"}},
    // VTSC (Vision Turn Speed Control): slow down for upcoming curves (0-250m)
    // using vision-only curvature (nagaspilot/controls/ngp_vtsc.py). Panel
    // toggle, matching EOP10's EOPVTSCEnabled. Default off.
    {"ngp_lon_vtsc", {PERSISTENT, BOOL, "0"}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_IsTakingSnapshot", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_StorageMissing", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSomResetTriggered", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSignatures", {CLEAR_ON_MANAGER_START, BYTES}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT, BOOL, "0"}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG, STRING}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT, BOOL}},
    {"TermsVersion", {PERSISTENT, STRING}},
    {"TrainingVersion", {PERSISTENT, STRING}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"EOPUpdateStatus", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"Version", {PERSISTENT, STRING}},

    // ---- EOP keys (RK3588 port + EOP features) ----
    {"EOPBluetoothPairingActive", {CLEAR_ON_MANAGER_START, STRING, "0"}},
    {"EOPBluetoothPairingAddr", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPBluetoothPairingPin", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPCameraCalibrationParams", {PERSISTENT, BYTES}},
    {"EOPAEBEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPALCCAllowAlways", {PERSISTENT, BOOL, "0"}},
    {"EOPALCCBrakeMode", {PERSISTENT, STRING, "Maintain"}},
    {"EOPALCCHoldAtStandstill", {PERSISTENT, BOOL, "0"}},
    {"EOPALCCSteeringModeOnBrake", {PERSISTENT, INT, "1"}},
    {"EOPALCCUnifiedEngagement", {PERSISTENT, BOOL, "0"}},
    // Driving mode: eco / normal / sport set acceleration profile, following style and adaptive gap together; custom (default) writes nothing.
    {"EOPDriveMode", {PERSISTENT, STRING, "custom"}},
    {"EOPAccelerationProfile", {PERSISTENT, STRING, "normal"}},
    {"EOPAdaptdEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPAdaptiveGapEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPAggressiveFollow", {PERSISTENT, FLOAT, "1.25"}},
    {"EOPAggressiveJerk", {PERSISTENT, FLOAT, "0.5"}},
    {"EOPAutoLaneChange", {PERSISTENT, BOOL, "0"}},
    {"EOPAutoTileEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPAutoTileWifiOnly", {PERSISTENT, BOOL, "1"}},
    {"EOPBlindSpotIndicator", {PERSISTENT, BOOL, "1"}},
    {"EOPBSDChimeEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPBEVWidgetEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPBSDEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPBSDMinSpeed", {PERSISTENT, FLOAT, "5.5"}},
    {"EOPBluetoothCANInterface", {PERSISTENT, STRING, "can0"}},
    {"EOPBluetoothEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPBluetoothPairWindow", {PERSISTENT, INT, "300"}},
    {"EOPBluetoothRadarEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPBLECornerPairs", {PERSISTENT, STRING, ""}},
    {"EOPBLERadarPairingOpen", {PERSISTENT, BOOL, "0"}},
    {"EOPBLERadarRoster", {PERSISTENT, STRING, ""}},  // extra ESP32 corner-radar WiFi STA MACs for BLE-only nodes (system/bluetoothd/ble_central.py)
    {"EOPCATEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPCATManualSR", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPCATManualSREnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPCATPersist", {PERSISTENT, STRING, ""}},
    {"EOPCurrentRegion", {PERSISTENT, STRING, ""}},
    {"EOPCurveSpeedDBPath", {PERSISTENT, STRING, "/data/shared/exopilot/curve.db"}},
    {"EOPCurveSpeedLearnEnabled", {PERSISTENT, BOOL, "1"}},
    // DLAT (Dynamic Lateral Profile, dlat.py) is a default, always-on
    // automatic Laneful/Laneless arbitration -- no user-selectable mode
    // param, matching dev/NGP10's design.
    {"EOPDLONCurvesEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLONForceStopsEnabled", {PERSISTENT, BOOL, "1"}},
    // Couples DLAT's own Laneful/Laneless arbitration (dlat.py) into DLON's
    // automatic switch: when DLAT has committed to Laneless, E2E's path-only
    // prediction fits better than lane-line-anchored ACC.
    {"EOPDLONLaneConfidenceEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLONLowSpeedEnabled", {PERSISTENT, BOOL, "1"}},
    // DLON (Dynamic Longitudinal Profile) is a default, always-on automatic
    // ACC/E2E switch -- no mode param: users cannot force pure E2E
    // (Experimental) or pure ACC directly, matching dev/NGP10's design.
    {"EOPDLONNavigationEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLONSignalEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLONSlowLeadEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLONSpeedLimitEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLONStopPredictionEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDLPCurvesEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPDeviceAudibleAlertMode", {PERSISTENT, STRING, "Std"}},
    {"EOPDeviceAutoShutdownIn", {PERSISTENT, INT, "0"}},
    {"EOPDeviceBeep", {PERSISTENT, BOOL, "1"}},
    {"EOPDeviceGoOffRoad", {PERSISTENT, BOOL, "0"}},
    {"EOPDeviceIsRhd", {PERSISTENT, BOOL, "0"}},
    {"EOPDeviceModelList", {PERSISTENT, STRING, ""}},
    {"EOPDeviceModelSelected", {PERSISTENT, STRING, ""}},
    {"EOPDeviceName", {PERSISTENT, STRING, "EXOPILOT"}},
    {"EOPFactoryCalibrated", {PERSISTENT, BOOL, "0"}},
    {"EOPFeatureAdvancedAnalytics", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureAiRouting", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureCloudBackup", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureCrossDeviceSync", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureDrivingScore", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureEmergencyAlert", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureFleetMode", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureLiveLocationShare", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureLiveTraffic", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureObdDashboard", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeaturePriorityTiles", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureRemoteCamera", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureRouteReplay", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureTelemetry", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFeatureTripSync", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPFollowingDistance", {PERSISTENT, STRING, "normal"}},
    {"EOPGlobaldEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPGridEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPGroundEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPHealthMonitorEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPHybridPlannerEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPIgnitionOn", {CLEAR_ON_MANAGER_START, BOOL, "1"}},
    {"EOPLCABSMEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPLCAConfirmRequired", {PERSISTENT, BOOL, "1"}},
    {"EOPLCAControllerEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPLCAGapEvalEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPLCALaneWidthEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPLCASurroundOverride", {PERSISTENT, BOOL, "0"}},
    {"EOPLCAdjacentLeadHandoff", {PERSISTENT, BOOL, "0"}},
    {"EOPLaneChangeDelay", {PERSISTENT, FLOAT, "1.0"}},
    {"EOPLanguage", {PERSISTENT, STRING, "en"}},
    {"EOPLatALCC", {PERSISTENT, BOOL, "1"}},
    {"EOPLatLCASpeed", {PERSISTENT, INT, "0"}},
    {"EOPLatRoadEdgeDetection", {PERSISTENT, BOOL, "1"}},
    {"EOPLeftCameraEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPLonExtRadar", {PERSISTENT, BOOL, "0"}},
    {"EOPMSLCAlert", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPMSLCEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPMSLCOffsetFixed", {PERSISTENT, INT, "0"}},
    {"EOPMSLCOffsetPercent", {PERSISTENT, INT, "0"}},
    {"EOPMTSCEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPMapdEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPMicAdaptiveLoudness", {PERSISTENT, BOOL, "1"}},
    {"EOPMinimumLaneWidth", {PERSISTENT, FLOAT, "3.0"}},
    {"EOPMonoDEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPMonoDMaxTracks", {PERSISTENT, INT, "64"}},
    {"EOPMonoDSceneSegEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPMonoDTeleEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPMonoDWideEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPMonoDYoloConf", {PERSISTENT, FLOAT, "0.5"}},
    {"EOPMultiCameraCalibEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPNSLCEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPNTRIPEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPNavBleEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPNavEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPNavPilotAddress", {PERSISTENT, STRING, ""}},
    {"EOPNavPilotPaired", {PERSISTENT, BOOL, "0"}},
    {"EOPNavVoiceEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPNudgeEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPOneLaneChange", {PERSISTENT, BOOL, "0"}},
    {"EOPOsmLocalizerEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPParkingMode", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPPointcloudEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPPointcloudMaxGB", {PERSISTENT, FLOAT, "4.0"}},
    {"EOPPointcloudRateHz", {PERSISTENT, INT, "5"}},
    {"EOPPointcloudUseGPU", {PERSISTENT, BOOL, "1"}},
    {"EOPPredictEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPRCDEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPRTKEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPRearCameraEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPRearCameraHeight", {PERSISTENT, INT, "720"}},
    {"EOPRearCameraWidth", {PERSISTENT, INT, "1280"}},
    {"EOPRecordEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPRecordSnap", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPRecorddImpactSensitivity", {PERSISTENT, INT, "50"}},
    {"EOPRecorddParkingEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPRecorddParkingHours", {PERSISTENT, FLOAT, "12.0"}},
    {"EOPRecorddPostBufferSec", {PERSISTENT, FLOAT, "30.0"}},
    {"EOPRecorddPreBufferSec", {PERSISTENT, FLOAT, "10.0"}},
    {"EOPRecorddQuality", {PERSISTENT, STRING, "medium"}},
    {"EOPRecorddSnapAutoG", {PERSISTENT, FLOAT, "2.0"}},
    {"EOPRecorddSnapImuMs", {PERSISTENT, INT, "500"}},
    // Pause lateral assistance with a turn signal on below this speed (mph); 0 = off. Shared with NGP10 (ngp_ prefix).
    {"EOPRedControllerEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPRelaxedFollow", {PERSISTENT, FLOAT, "1.75"}},
    {"EOPRelaxedJerk", {PERSISTENT, FLOAT, "1.0"}},
    {"EOPRightCameraEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPRoadHDR", {PERSISTENT, STRING, "hdr4"}},
    {"EOPSGMConfidenceThreshold", {PERSISTENT, FLOAT, "0.7"}},
    {"EOPSGMLocalizerEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPSGMMapPath", {PERSISTENT, STRING, "/data/maps/sgm"}},
    {"EOPSGMMaxRange", {PERSISTENT, FLOAT, "100.0"}},
    {"EOPSGMMode", {PERSISTENT, STRING, "live"}},
    {"EOPSLCConfirmHigher", {PERSISTENT, BOOL, "1"}},
    {"EOPSLCConfirmLower", {PERSISTENT, BOOL, "1"}},
    {"EOPSLCOffset1", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSLCOffset2", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSLCOffset3", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSLCOffset4", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSLCOffset5", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSLCOffset6", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSLCOffset7", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPSOCControllerEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPSPPAutoReconnect", {PERSISTENT, BOOL, "1"}},
    {"EOPSPPChannel", {PERSISTENT, INT, "1"}},
    {"EOPSPPDeviceName", {PERSISTENT, STRING, ""}},
    {"EOPSPPEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPSPPMaxClients", {PERSISTENT, INT, "3"}},
    {"EOPSPPPairedDevice", {PERSISTENT, STRING, ""}},
    {"EOPSPPRpcRequest", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPSPPRpcResponse", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPSQSCEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPSQSCLookaheadEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPSQSCProfile", {PERSISTENT, STRING, "balanced"}},
    {"EOPSQSCRecordMinLeadM", {PERSISTENT, FLOAT, "40.0"}},
    {"EOPSQSCRecordMinQuality", {PERSISTENT, FLOAT, "0.25"}},
    {"EOPSQSCRecordMinSpeedKph", {PERSISTENT, FLOAT, "18.0"}},
    {"EOPSQSCSensitivity", {PERSISTENT, FLOAT, "1.0"}},
    {"EOPSQSCSmoothing", {PERSISTENT, FLOAT, "2.0"}},
    {"EOPSQSCUseLearnedSpeed", {PERSISTENT, BOOL, "1"}},
    {"EOPSafetyDriverTorqueThreshold", {PERSISTENT, INT, "200"}},
    {"EOPSafetyEventLogEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPSafetyEventLogPath", {PERSISTENT, STRING, "/data/safety_violations.log"}},
    {"EOPSafetyHeartbeatTimeout", {PERSISTENT, INT, "200"}},
    {"EOPSafetyMaxAccel", {PERSISTENT, INT, "340"}},
    {"EOPSafetyMaxAngleError", {PERSISTENT, INT, "240"}},
    {"EOPSafetyMaxSteeringAngle", {PERSISTENT, INT, "2700"}},
    {"EOPSafetyMaxSteeringRate", {PERSISTENT, INT, "200"}},
    {"EOPSafetyMessageTimeout", {PERSISTENT, INT, "1200"}},
    {"EOPSafetyMinAccel", {PERSISTENT, INT, "312"}},
    {"EOPShockDepthM", {PERSISTENT, FLOAT, "0.08"}},
    {"EOPShockDetection", {PERSISTENT, BOOL, "1"}},
    {"EOPShockDuration", {PERSISTENT, INT, "3"}},
    {"EOPShockHeightM", {PERSISTENT, FLOAT, "0.05"}},
    {"EOPShockSpeedLimit", {PERSISTENT, INT, "15"}},
    {"EOPShockThreshold", {PERSISTENT, FLOAT, "2.5"}},
    {"EOPSideCameraHeight", {PERSISTENT, INT, "720"}},
    {"EOPSideCameraWidth", {PERSISTENT, INT, "1280"}},
    {"EOPSideCamerasEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPSideCamerasSwapped", {PERSISTENT, BOOL, "0"}},
    // One-shot: UI sets it, camera_calibrationd.py resets side/rear
    // calibration and clears it back to false. Not PERSISTENT -- a stuck
    // "true" across a manager restart would silently reset calibration on
    // every boot, same reasoning as DoReboot/DoShutdown.
    {"EOPSideRearCalibReset", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    // Empty means "the board that is running" -- the sim bridge falls back
    // to HARDWARE.get_device_type(). A literal here was one board's name
    // baked into a branch-independent default.
    {"EOPSimPlatform", {PERSISTENT, STRING, ""}},
    {"EOPSimScenario", {PERSISTENT, STRING, ""}},
    {"EOPSimWeather", {PERSISTENT, STRING, ""}},
    {"EOPSpeedLimitOffset", {PERSISTENT, INT, "0"}},
    {"EOPStandardFollow", {PERSISTENT, FLOAT, "1.45"}},
    {"EOPStandardJerk", {PERSISTENT, FLOAT, "1.0"}},
    {"EOPStereoEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPSubscriptionCheckInterval", {PERSISTENT, INT, "30"}},
    {"EOPSubscriptionDeviceId", {PERSISTENT, STRING, ""}},
    {"EOPSubscriptionExpiry", {PERSISTENT, STRING, ""}},
    {"EOPSubscriptionSignature", {PERSISTENT | DONT_LOG, STRING, ""}},
    {"EOPSubscriptionSkipVerify", {PERSISTENT, BOOL, "0"}},
    {"EOPSubscriptionTier", {PERSISTENT, STRING, "none"}},
    {"EOPSubscriptionToken", {PERSISTENT | DONT_LOG, STRING, ""}},
    {"EOPSurfaceEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPSurfaceGridRange", {PERSISTENT, FLOAT, "60.0"}},
    {"EOPSurfaceGridResolution", {PERSISTENT, FLOAT, "0.25"}},
    {"EOPSurfaceGridWidth", {PERSISTENT, FLOAT, "30.0"}},
    {"EOPSurfaceLongHorizon", {PERSISTENT, BOOL, "1"}},
    {"EOPSurfaceLongRange", {PERSISTENT, FLOAT, "100.0"}},
    {"EOPTJAEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPTJAMaxHoldMinutes", {PERSISTENT, INT, "10"}},
    {"EOPTLSCEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPTSCTargetLatAccel", {PERSISTENT, FLOAT, "1.8"}},
    {"EOPTSCTargetLatAccelMedium", {PERSISTENT, FLOAT, "1.8"}},
    {"EOPTSCTargetLatAccelMild", {PERSISTENT, FLOAT, "2.0"}},
    {"EOPTSCTargetLatAccelSharp", {PERSISTENT, FLOAT, "1.5"}},
    {"EOPTTSAlertsEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPTTSVoice", {PERSISTENT, STRING, "auto"}},
    {"EOPTTSVolume", {PERSISTENT, FLOAT, "1.0"}},
    {"EOPTeleEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPTeleHDR", {PERSISTENT, STRING, "hdr4"}},
    {"EOPTileLastUpdate", {PERSISTENT, INT, "0"}},
    {"EOPTouchEventNode", {PERSISTENT, STRING, ""}},
    {"EOPTrackEnabled", {PERSISTENT, BOOL, "1"}},
    {"EOPTrafficFollow", {PERSISTENT, FLOAT, "1.35"}},
    {"EOPTrafficJerk", {PERSISTENT, FLOAT, "0.8"}},
    {"EOPTripAStartDistance", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripAStartTime", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripBStartDistance", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripBStartTime", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripCurrentEngagementRatio", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripLastDistance", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripLastDuration", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripLastMaxAccel", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripLastOverrideFreeDistance", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripLastPersonalityTime", {PERSISTENT, STRING, ""}},
    {"EOPTripLifetimeEngagementRatio", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripMode", {PERSISTENT, INT, "0"}},
    {"EOPTripTotalDistance", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripTotalDrives", {PERSISTENT, INT, "0"}},
    {"EOPTripDailyStats", {PERSISTENT, STRING}},  // JSON {date: [distance, onroad_time, engaged_time, drives]}, last 7 days
    {"EOPTripUptimeEngaged", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPTripUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"EOPUIBrightness", {PERSISTENT, INT, "0"}},
    {"EOPUIDisplayMode", {PERSISTENT, BOOL, "0"}},
    {"EOPUIHideHudSpeedKph", {PERSISTENT, INT, "0"}},
    {"EOPUIRadarTracks", {PERSISTENT, BOOL, "0"}},
    {"EOPUIRainbow", {PERSISTENT, BOOL, "0"}},
    {"EOPUploadCurrentHeaders", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPUploadCurrentId", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPUploadCurrentPath", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPUploadCurrentProgress", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPUploadCurrentSize", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPUploadCurrentUrl", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPVTSCEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPValhallaUrl", {PERSISTENT, STRING, ""}},
    {"EOPVehicleType", {PERSISTENT, STRING, "SUV_C"}},
    {"EOPWideHDR", {PERSISTENT, STRING, "hdr4"}},
    {"EOPFactoryCalibrationParams", {PERSISTENT, BYTES}},
    {"EOPCarMake", {PERSISTENT, STRING}},
    {"EOPCarType", {PERSISTENT, STRING}},
    {"EOPCarVin", {PERSISTENT, STRING}},
    // ASM2464PD / Chestnut eGPU driving path (mirrors upstream UsbGpu*; named
    // Egpu* to cover both our own flashed firmware and comma's Chestnut
    // firmware on the same physical chip).
    {"EOPChestnutDrivingEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPChestnutDrivingLoading", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPChestnutDrivingActive", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPCurrentMCAPRoute", {CLEAR_ON_MANAGER_START, STRING}},
    {"EOPWakeEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPVoiceWakeTrigger", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPCloudVoiceEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPVoiceProcessing", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPVoiceRecording", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPVoiceEnabled", {PERSISTENT, BOOL}},
    {"EOPLastGPSAltitude", {PERSISTENT, STRING}},
    {"EOPLastGPSLatitude", {PERSISTENT, STRING}},
    {"EOPLastGPSLongitude", {PERSISTENT, STRING}},
    // BRSC: Bumpy Road Speed Controller — shared across EOP10/NGP10/EDP10 via
    // nagaspilot/controls/ngp_brsc.py; NGP prefix (not EOP) marks features
    // ported verbatim across all three branches. See docs/eop/03_Software/Controllers/BRSC.md
    {"EOPNavPilotOAuthEmail", {PERSISTENT | DONT_LOG, STRING}},
    {"EOPNavPilotOAuthToken", {PERSISTENT | DONT_LOG, STRING}},
    {"EOPOpenBLTFirmwareVersion", {PERSISTENT, STRING}},
    {"EOPOpenBLTState", {CLEAR_ON_MANAGER_START, STRING, "idle"}},
    {"EOPOpenBLTUpdateAvailable", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"EOPUbloxAssistNowToken", {PERSISTENT | DONT_LOG, STRING}},
    {"EOPNavDestination", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPNavDestinationWaypoints", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPNeuralNetworkLateralControl", {PERSISTENT, BOOL, "0"}},
    {"EOPSpeedLimitPolicy", {PERSISTENT, INT, "4"}},
    {"EOPSteamDAuthToken", {PERSISTENT | DONT_LOG, STRING, ""}},
    {"EOPSteamDControlRequest", {CLEAR_ON_MANAGER_START, STRING, ""}},
    {"EOPSteamDEnabled", {PERSISTENT, BOOL, "0"}},
    {"EOPSteamDGeofencePolygon", {PERSISTENT, STRING, ""}},
    {"EOPSteamDJoystickInput", {PERSISTENT, BOOL, "1"}},
    {"EOPSteamDRemoteControl", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL, "0"}},
};
