#pragma once

#include <string>
#include <unordered_map>

#include "cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT, BOOL}},
    {"AlwaysOnDM", {PERSISTENT, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {PERSISTENT, BOOL, "0"}},
    {"DisablePowerDown", {PERSISTENT, BOOL}},
    {"DisableUpdates", {PERSISTENT, BOOL}},
    {"DisengageOnAccelerator", {PERSISTENT, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"AlphaLongitudinalEnabled", {PERSISTENT | DEVELOPMENT_ONLY, BOOL}},
    {"ExperimentalMode", {PERSISTENT, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT, STRING}},
    {"GithubUsername", {PERSISTENT, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT, STRING}},
    {"GsmMetered", {PERSISTENT, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT, BOOL}},
    {"IsMetric", {PERSISTENT, BOOL}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsOnroad", {PERSISTENT, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTakingSnapshot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT, STRING, "main_en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_IsTakingSnapshot", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_StorageMissing", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSomResetTriggered", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSignatures", {CLEAR_ON_MANAGER_START, BYTES}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT, BOOL, "0"}},
    {"RecordFront", {PERSISTENT, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG, STRING}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT, BOOL}},
    {"TermsVersion", {PERSISTENT, STRING}},
    {"TrainingVersion", {PERSISTENT, STRING}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"Version", {PERSISTENT, STRING}},

    // NagasPilot Device Parameters
    {"np_device_monitoring_disable", {PERSISTENT, BOOL, "0"}},
    {"np_device_beep", {PERSISTENT, BOOL, "0"}},
    {"np_device_go_off_road", {CLEAR_ON_MANAGER_START, BOOL}},
    {"np_device_reset_conf", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"np_device_alert_mode", {PERSISTENT, INT, "0"}},
    {"np_device_auto_shutdown", {PERSISTENT, INT, "-5"}},
    {"np_device_model_selected", {PERSISTENT, STRING}},
    {"np_device_model_list", {PERSISTENT, STRING}},
    {"np_device_last_log", {PERSISTENT, STRING}},
    {"np_device_rhd", {PERSISTENT, BOOL, "0"}},
    {"np_device_audible_alert_mode", {PERSISTENT, INT, "0"}},

    // Dynamic Lane Profile (DLP) Parameters
    {"np_dlp_enable", {PERSISTENT, BOOL, "1"}},
    {"np_dlp_lca_enable", {PERSISTENT, BOOL, "1"}},
    {"np_dlp_laneless_enable", {PERSISTENT, BOOL, "1"}},
    {"np_dlp_laneless_min_confidence", {PERSISTENT, FLOAT, "0.6"}},
    {"np_dlp_laneless_lateral_factor", {PERSISTENT, FLOAT, "0.7"}},
    {"np_dlp_laneless_transition_time", {PERSISTENT, FLOAT, "2.0"}},
    {"np_dlp_laneless_max_speed", {PERSISTENT, FLOAT, "80.0"}},
    {"np_dlp_adaptive_timing", {PERSISTENT, BOOL, "1"}},
    {"np_dlp_weather_integration", {PERSISTENT, BOOL, "1"}},
    {"np_dlp_min_lane_width", {PERSISTENT, FLOAT, "2.5"}},
    {"np_dlp_max_lateral_accel", {PERSISTENT, FLOAT, "2.5"}},
    {"np_dlp_confidence_threshold", {PERSISTENT, FLOAT, "0.7"}},

    // Always Lane Centering Control (ALCC) Parameters
    {"np_alcc_enable", {PERSISTENT, BOOL, "0"}},
    {"np_alcc_mode", {PERSISTENT, STRING, "DISABLED"}},
    {"np_alcc_allow_standalone", {PERSISTENT, STRING, "DISABLED"}},
    {"np_alcc_hold_at_standstill", {PERSISTENT, BOOL, "0"}},
    {"np_alcc_brake_mode", {PERSISTENT, STRING, "PAUSE"}},
    {"np_alcc_confidence_threshold", {PERSISTENT, FLOAT, "0.7"}},
    {"np_alcc_state", {PERSISTENT, STRING}},
    {"np_alcc_lane_confidence", {PERSISTENT, FLOAT}},
    {"np_alcc_lane_width_left", {PERSISTENT, FLOAT}},
    {"np_alcc_lane_width_right", {PERSISTENT, FLOAT}},
    {"np_alcc_blindspot_clear", {PERSISTENT, BOOL}},
    {"np_alcc_lane_change_ready", {PERSISTENT, BOOL}},
    {"np_alcc_target_lane", {PERSISTENT, STRING}},

    // Lane Change Assist (LCA) Parameters
    {"np_lca_mode", {PERSISTENT, STRING, "NUDGE"}},
    {"np_lca_min_speed", {PERSISTENT, INT, "60"}},
    {"np_lca_auto_delay", {PERSISTENT, FLOAT, "0.5"}},
    {"np_lca_delay", {PERSISTENT, FLOAT, "0.5"}},
    {"np_lca_bsm_delay", {PERSISTENT, BOOL, "1"}},
    {"np_lca_one_per_signal", {PERSISTENT, BOOL, "1"}},
    {"np_lca_torque_threshold", {PERSISTENT, FLOAT, "0.5"}},
    {"np_lca_override_torque", {PERSISTENT, FLOAT, "2.0"}},
    {"np_lca_confidence_threshold", {PERSISTENT, FLOAT, "0.7"}},
    {"np_lca_max_curvature", {PERSISTENT, FLOAT, "0.01"}},
    {"np_lca_intention_enable", {PERSISTENT, BOOL, "1"}},
    {"np_lca_auto_confirm_time", {PERSISTENT, FLOAT, "0.5"}},
    {"np_lca_intention_timeout", {PERSISTENT, FLOAT, "10.0"}},
    {"np_dlp_lca_mode", {PERSISTENT, STRING, "NUDGE"}},
    {"np_dlp_lca_delay", {PERSISTENT, FLOAT, "0.5"}},
    {"np_dlp_lca_bsm_delay", {PERSISTENT, BOOL, "1"}},
    {"np_dlp_lca_min_speed", {PERSISTENT, FLOAT, "20.0"}},

    // Turn Speed Controller (TSC) Parameters
    {"np_tsc_enable", {PERSISTENT, BOOL, "1"}},
    {"np_tsc_use_map", {PERSISTENT, BOOL, "1"}},
    {"np_tsc_use_vision", {PERSISTENT, BOOL, "1"}},
    {"np_tsc_calibrate", {PERSISTENT, BOOL, "1"}},
    {"np_tsc_curvature_data", {PERSISTENT, STRING}},
    {"np_tsc_lateral_acceleration", {PERSISTENT, FLOAT}},
    {"np_tsc_calibration_progress", {PERSISTENT, FLOAT}},
    {"np_tsc_training_active", {PERSISTENT, BOOL}},
    {"np_tsc_calibration_complete", {PERSISTENT, BOOL}},
    {"np_tsc_last_calibration_save", {PERSISTENT, FLOAT}},
    {"np_cat_enable", {PERSISTENT, BOOL, "0"}},
    {"np_cat_status", {PERSISTENT, JSON}},
    {"np_cat_persist", {PERSISTENT, JSON}},
    {"np_stack_status", {PERSISTENT, JSON}},
    {"np_cat_manual_sr_enable", {PERSISTENT, BOOL, "0"}},
    {"np_cat_manual_sr", {PERSISTENT, FLOAT}},
    {"np_cat_debug_onroad", {PERSISTENT, BOOL, "0"}},    // Show CAT debug on HUD
    {"np_stack_debug_onroad", {PERSISTENT, BOOL, "0"}},  // Show DLP/TSC/DEM debug on HUD

    // UI Parameters
    {"np_ui_hud_hide_speed", {PERSISTENT, INT, "40"}},
    {"np_ui_rainbow_path", {PERSISTENT, BOOL, "1"}},
    {"np_ui_radar_tracks", {PERSISTENT, BOOL, "0"}},
    {"np_ui_display_mode", {PERSISTENT, BOOL, "0"}},

    // Road Edge Detection (RED)
    {"np_red_enable", {PERSISTENT, BOOL, "1"}},

    // External Radar
    {"np_ext_radar_enable", {PERSISTENT, BOOL, "0"}},

    // Developer Parameters
    {"np_dev_dashy", {PERSISTENT, INT, "0"}},
    {"np_dev_delay_loggerd", {PERSISTENT, INT, "0"}},

    // Trip Management
    {"NagasPilotStats", {PERSISTENT | DONT_LOG, STRING}},
    {"np_total_distance", {PERSISTENT, FLOAT, "0.0"}},
    {"np_total_uptime_onroad", {PERSISTENT, FLOAT, "0.0"}},
    {"np_total_engaged_time", {PERSISTENT, FLOAT, "0.0"}},
    {"np_total_drives", {PERSISTENT, INT, "0"}},
    {"np_trip_a_start_distance", {PERSISTENT, FLOAT, "0.0"}},
    {"np_trip_a_start_time", {PERSISTENT, FLOAT, "0.0"}},
    {"np_trip_b_start_distance", {PERSISTENT, FLOAT, "0.0"}},
    {"np_trip_b_start_time", {PERSISTENT, FLOAT, "0.0"}},
    {"np_trip_mode", {PERSISTENT, INT, "0"}},
    {"np_trip_weekly_stats", {PERSISTENT | DONT_LOG, JSON}},
    {"np_trip_reset_request", {CLEAR_ON_MANAGER_START, STRING}},
    {"np_trip_reset_status", {CLEAR_ON_MANAGER_START, STRING}},
};
